from .empleado import Empleado
from .persona import Persona
from .usuario import Usuario
from .logro import Logro
from .logro_empleado import LogroEmpleado
from .objetivo import Objetivo
from .objetivo_empleado import ObjetivoEmpleado
from .habilidad import Habilidad
from .habilidad_empleado import HabilidadEmpleado
from .capacitacion import Capacitacion
from .capacitacion_empleado import CapacitacionEmpleado
from .competencia import Competencia
from .competencia_empleado import CompetenciaEmpleado
from .institucion import Institucion
from .institucion_capacitacion import InstitucionCapacitacion
from .tipo_criterio import TipoCriterio
from .criterio_evaluacion import CriterioEvaluacion
from .evaluacion import Evaluacion
from .desempeno_criterio import DesempenoCriterio
from .historial_contrato import HistorialContrato
from .tipo_contrato import TipoContrato
from .vacaciones_disponibles import VacacionesDisponibles
from .vacaciones_solicitud import VacacionesSolicitud
from .solicitud import Solicitud
from .cargo_departamento import CargoDepartamento
from .departamento import Departamento
from .cargo import Cargo
from .empleado_cargo import EmpleadoCargo
from .nomina import Nomina
from .descuento import Descuento
from .descuento_empleado_nomina import DescuentoEmpleadoNomina
from .beneficio import Beneficio
from .beneficio_empleado_nomina import BeneficioEmpleadoNomina
from .historial_sueldo_base import HistorialSueldoBase
from .nomina_historial_sueldo import NominaHistorialSueldo
from .historial_asistencia import HistorialAsistencia
