# Generated by Django 5.1.6 on 2025-03-19 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficio',
            fields=[
                ('id_beneficio', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'beneficio',
            },
        ),
        migrations.CreateModel(
            name='Capacitacion',
            fields=[
                ('id_capacitacion', models.AutoField(db_column='id_capacitacion', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
            ],
            options={
                'db_table': 'capacitacion',
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id_cargo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('total_vacantes', models.IntegerField()),
            ],
            options={
                'db_table': 'cargo',
            },
        ),
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('id_competencia', models.AutoField(db_column='id_competencia', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'competencias',
            },
        ),
        migrations.CreateModel(
            name='CriterioEvaluacion',
            fields=[
                ('id_criterio', models.AutoField(db_column='id_criterio', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('ponderacion', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'criterio_evaluacion',
            },
        ),
        migrations.CreateModel(
            name='Descuento',
            fields=[
                ('id_descuento', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=100)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'descuento',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id_persona', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=20, unique=True)),
                ('email', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_nacimiento', models.DateField()),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_persona', models.CharField(choices=[('empleado', 'Empleado'), ('postulante', 'Postulante')], max_length=10)),
            ],
            options={
                'db_table': 'persona',
            },
        ),
        migrations.CreateModel(
            name='Habilidad',
            fields=[
                ('id_habilidad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'habilidad',
            },
        ),
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id_institucion', models.AutoField(db_column='id_institucion', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('correo', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'institucion',
            },
        ),
        migrations.CreateModel(
            name='Logro',
            fields=[
                ('id_logro', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
            ],
            options={
                'db_table': 'logros',
            },
        ),
        migrations.CreateModel(
            name='Nomina',
            fields=[
                ('id_nomina', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_generacion', models.DateField()),
                ('monto_bruto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_neto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cant_dias_trabajados', models.IntegerField()),
                ('total_descuentos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(max_length=50)),
                ('periodo', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'nomina',
            },
        ),
        migrations.CreateModel(
            name='Objetivo',
            fields=[
                ('id_objetivo', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'objetivos',
            },
        ),
        migrations.CreateModel(
            name='TipoContrato',
            fields=[
                ('id_contrato', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'tipo_contrato',
            },
        ),
        migrations.CreateModel(
            name='TipoCriterio',
            fields=[
                ('id_tipo_criterio', models.AutoField(db_column='id_tipo_criterio', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'tipo_criterio',
            },
        ),
        migrations.CreateModel(
            name='CapacitacionEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateField()),
                ('estado', models.CharField(max_length=50)),
                ('id_capacitacion', models.ForeignKey(db_column='id_capacitacion', on_delete=django.db.models.deletion.CASCADE, to='app_principal.capacitacion')),
            ],
            options={
                'db_table': 'capacitacion_empleado',
            },
        ),
        migrations.CreateModel(
            name='CargoDepartamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cargo', models.ForeignKey(db_column='id_cargo', on_delete=django.db.models.deletion.CASCADE, to='app_principal.cargo')),
            ],
            options={
                'db_table': 'cargo_departamento',
            },
        ),
        migrations.CreateModel(
            name='CompetenciaEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_competencia', models.ForeignKey(db_column='id_competencia', on_delete=django.db.models.deletion.CASCADE, to='app_principal.competencia')),
            ],
            options={
                'db_table': 'competencia_empleado',
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id_departamento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('cargos', models.ManyToManyField(related_name='departamento_cargos', through='app_principal.CargoDepartamento', to='app_principal.cargo')),
            ],
            options={
                'db_table': 'departamento',
            },
        ),
        migrations.AddField(
            model_name='cargodepartamento',
            name='id_departamento',
            field=models.ForeignKey(db_column='id_departamento', on_delete=django.db.models.deletion.CASCADE, to='app_principal.departamento'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='departamentos',
            field=models.ManyToManyField(related_name='cargos_departamento', through='app_principal.CargoDepartamento', to='app_principal.departamento'),
        ),
        migrations.CreateModel(
            name='DesempenoCriterio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_evaluacion', models.DateField()),
                ('id_criterio', models.ForeignKey(db_column='id_criterio', on_delete=django.db.models.deletion.CASCADE, to='app_principal.criterioevaluacion')),
            ],
            options={
                'db_table': 'desempeno_criterio',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='app_principal.persona')),
                ('id_empleado', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('inactivo', 'Inactivo'), ('en licencia', 'En licencia'), ('suspendido', 'Suspendido'), ('en prueba', 'En Prueba'), ('jubilado', 'Jubilado')], max_length=20)),
            ],
            options={
                'db_table': 'empleado',
            },
            bases=('app_principal.persona',),
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_evaluacion', models.DateField()),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('comentarios', models.CharField(blank=True, max_length=255, null=True)),
                ('calificacion_final', models.DecimalField(decimal_places=2, max_digits=5)),
                ('criterios', models.ManyToManyField(related_name='evaluaciones', through='app_principal.DesempenoCriterio', to='app_principal.criterioevaluacion')),
                ('id_empleado', models.ForeignKey(db_column='id_empleado', on_delete=django.db.models.deletion.CASCADE, to='app_principal.empleado')),
            ],
            options={
                'db_table': 'evaluacion',
                'unique_together': {('id_empleado', 'fecha_evaluacion')},
            },
        ),
        migrations.AddField(
            model_name='desempenocriterio',
            name='id_evaluacion',
            field=models.ForeignKey(db_column='id_evaluacion', on_delete=django.db.models.deletion.CASCADE, to='app_principal.evaluacion'),
        ),
        migrations.CreateModel(
            name='HistorialSueldoBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_sueldo', models.DateField()),
                ('sueldo_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_principal.cargo')),
            ],
            options={
                'db_table': 'historial_sueldo_base',
                'unique_together': {('fecha_sueldo', 'cargo')},
            },
        ),
        migrations.CreateModel(
            name='InstitucionCapacitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_capacitacion', models.ForeignKey(db_column='id_capacitacion', on_delete=django.db.models.deletion.CASCADE, to='app_principal.capacitacion')),
                ('id_institucion', models.ForeignKey(db_column='id_institucion', on_delete=django.db.models.deletion.CASCADE, to='app_principal.institucion')),
            ],
            options={
                'db_table': 'institucion_capacitacion',
                'unique_together': {('id_institucion', 'id_capacitacion')},
            },
        ),
        migrations.AddField(
            model_name='capacitacion',
            name='instituciones',
            field=models.ManyToManyField(related_name='capacitaciones', through='app_principal.InstitucionCapacitacion', to='app_principal.institucion'),
        ),
        migrations.CreateModel(
            name='DescuentoEmpleadoNomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descuento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_principal.descuento')),
                ('nomina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_principal.nomina')),
            ],
            options={
                'db_table': 'descuento_empleado_nomina',
            },
        ),
        migrations.CreateModel(
            name='BeneficioEmpleadoNomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beneficio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_principal.beneficio')),
                ('nomina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_principal.nomina')),
            ],
            options={
                'db_table': 'beneficio_empleado_nomina',
            },
        ),
        migrations.CreateModel(
            name='NominaHistorialSueldo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('historial_sueldo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_principal.historialsueldobase')),
                ('nomina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_principal.nomina')),
            ],
            options={
                'db_table': 'nomina_historial_sueldo',
                'unique_together': {('nomina', 'historial_sueldo')},
            },
        ),
        migrations.AddField(
            model_name='nomina',
            name='historial_sueldos',
            field=models.ManyToManyField(related_name='nominas', through='app_principal.NominaHistorialSueldo', to='app_principal.historialsueldobase'),
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id_solicitud', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_postulacion', models.DateField()),
                ('estado_postulacion', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], max_length=10)),
                ('cargo', models.ForeignKey(db_column='id_cargo', on_delete=django.db.models.deletion.CASCADE, to='app_principal.cargo')),
                ('persona', models.ForeignKey(db_column='id_persona', on_delete=django.db.models.deletion.CASCADE, to='app_principal.persona')),
            ],
            options={
                'db_table': 'solicitud',
            },
        ),
        migrations.AddField(
            model_name='persona',
            name='cargos',
            field=models.ManyToManyField(related_name='postulantes', through='app_principal.Solicitud', to='app_principal.cargo'),
        ),
        migrations.AddField(
            model_name='criterioevaluacion',
            name='id_tipo_criterio',
            field=models.ForeignKey(db_column='id_tipo_criterio', on_delete=django.db.models.deletion.CASCADE, to='app_principal.tipocriterio'),
        ),
        migrations.AlterUniqueTogether(
            name='cargodepartamento',
            unique_together={('id_cargo', 'id_departamento')},
        ),
        migrations.CreateModel(
            name='VacacionesSolicitud',
            fields=[
                ('id_solicitud', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_solicitud', models.DateField()),
                ('fecha_inicio_estimada', models.DateField()),
                ('fecha_fin_estimada', models.DateField()),
                ('cant_dias_solicitados', models.IntegerField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], max_length=10)),
                ('id_empleado', models.ForeignKey(db_column='id_empleado', on_delete=django.db.models.deletion.CASCADE, to='app_principal.empleado')),
            ],
            options={
                'db_table': 'vacaciones_solicitud',
            },
        ),
        migrations.CreateModel(
            name='ObjetivoEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_objetivo', models.ForeignKey(db_column='id_objetivo', on_delete=django.db.models.deletion.CASCADE, to='app_principal.objetivo')),
                ('id_empleado', models.ForeignKey(db_column='id_empleado', on_delete=django.db.models.deletion.CASCADE, to='app_principal.empleado')),
            ],
            options={
                'db_table': 'objetivos_empleado',
                'unique_together': {('id_objetivo', 'id_empleado')},
            },
        ),
        migrations.AddField(
            model_name='nomina',
            name='id_empleado',
            field=models.ForeignKey(db_column='id_empleado', on_delete=django.db.models.deletion.CASCADE, to='app_principal.empleado'),
        ),
        migrations.CreateModel(
            name='LogroEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_logro', models.ForeignKey(db_column='id_logros', on_delete=django.db.models.deletion.CASCADE, to='app_principal.logro')),
                ('id_empleado', models.ForeignKey(db_column='id_empleado', on_delete=django.db.models.deletion.CASCADE, to='app_principal.empleado')),
            ],
            options={
                'db_table': 'logros_empleado',
                'unique_together': {('id_logro', 'id_empleado')},
            },
        ),
        migrations.CreateModel(
            name='HistorialContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('condiciones', models.CharField(max_length=255)),
                ('id_contrato', models.ForeignKey(db_column='id_contrato', on_delete=django.db.models.deletion.CASCADE, to='app_principal.tipocontrato')),
                ('id_empleado', models.ForeignKey(db_column='id_empleado', on_delete=django.db.models.deletion.CASCADE, to='app_principal.empleado')),
            ],
            options={
                'db_table': 'historial_contrato',
                'unique_together': {('id_empleado', 'fecha_inicio')},
            },
        ),
        migrations.CreateModel(
            name='HabilidadEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_habilidad', models.ForeignKey(db_column='id_habilidad', on_delete=django.db.models.deletion.CASCADE, to='app_principal.habilidad')),
                ('id_empleado', models.ForeignKey(db_column='id_empleado', on_delete=django.db.models.deletion.CASCADE, to='app_principal.empleado')),
            ],
        ),
        migrations.AddField(
            model_name='empleado',
            name='beneficios',
            field=models.ManyToManyField(related_name='empleados', through='app_principal.BeneficioEmpleadoNomina', to='app_principal.beneficio'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='capacitaciones',
            field=models.ManyToManyField(related_name='empleados', through='app_principal.CapacitacionEmpleado', to='app_principal.capacitacion'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='competencias',
            field=models.ManyToManyField(related_name='empleados', through='app_principal.CompetenciaEmpleado', to='app_principal.competencia'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='contratos',
            field=models.ManyToManyField(related_name='empleados', through='app_principal.HistorialContrato', to='app_principal.tipocontrato'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='descuentos',
            field=models.ManyToManyField(related_name='empleados', through='app_principal.DescuentoEmpleadoNomina', to='app_principal.descuento'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='habilidades',
            field=models.ManyToManyField(related_name='empleados', through='app_principal.HabilidadEmpleado', to='app_principal.habilidad'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='logros',
            field=models.ManyToManyField(related_name='empleados', through='app_principal.LogroEmpleado', to='app_principal.logro'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='nominas',
            field=models.ManyToManyField(related_name='empleados', through='app_principal.DescuentoEmpleadoNomina', to='app_principal.nomina'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='objetivos',
            field=models.ManyToManyField(related_name='empleados', through='app_principal.ObjetivoEmpleado', to='app_principal.objetivo'),
        ),
        migrations.AddField(
            model_name='desempenocriterio',
            name='id_empleado',
            field=models.ForeignKey(db_column='id_empleado', on_delete=django.db.models.deletion.CASCADE, to='app_principal.empleado'),
        ),
        migrations.AddField(
            model_name='descuentoempleadonomina',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_principal.empleado'),
        ),
        migrations.AddField(
            model_name='competenciaempleado',
            name='id_empleado',
            field=models.ForeignKey(db_column='id_empleado', on_delete=django.db.models.deletion.CASCADE, to='app_principal.empleado'),
        ),
        migrations.AddField(
            model_name='capacitacionempleado',
            name='id_empleado',
            field=models.ForeignKey(db_column='id_empleado', on_delete=django.db.models.deletion.CASCADE, to='app_principal.empleado'),
        ),
        migrations.AddField(
            model_name='beneficioempleadonomina',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_principal.empleado'),
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(max_length=50, unique=True)),
                ('correo', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('rol', models.CharField(choices=[('admin', 'Admin'), ('empleado', 'Empleado'), ('gerente', 'Gerente')], default='empleado', max_length=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('empleado', models.OneToOneField(db_column='id_empleado', on_delete=django.db.models.deletion.CASCADE, to='app_principal.empleado')),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='VacacionesDisponibles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('cantidad_dias_disponibles', models.IntegerField()),
                ('id_empleado', models.ForeignKey(db_column='id_empleado', on_delete=django.db.models.deletion.CASCADE, to='app_principal.empleado')),
            ],
            options={
                'db_table': 'vacaciones_disponibles',
                'unique_together': {('id_empleado', 'fecha')},
            },
        ),
        migrations.CreateModel(
            name='HistorialAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asistencia', models.DateField()),
                ('hora_entrada', models.TimeField()),
                ('hora_salida', models.TimeField(blank=True, null=True)),
                ('empleado', models.ForeignKey(db_column='id_empleado', on_delete=django.db.models.deletion.CASCADE, to='app_principal.empleado')),
            ],
            options={
                'db_table': 'historial_asistencia',
                'unique_together': {('empleado', 'fecha_asistencia', 'hora_entrada')},
            },
        ),
        migrations.CreateModel(
            name='EmpleadoCargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateField()),
                ('fecha_desasignado', models.DateField(blank=True, null=True)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_principal.cargo')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_principal.empleado')),
            ],
            options={
                'db_table': 'empleado_cargo',
                'unique_together': {('empleado', 'cargo', 'fecha_asignacion')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='desempenocriterio',
            unique_together={('id_criterio', 'id_empleado', 'id_evaluacion', 'fecha_evaluacion')},
        ),
        migrations.AlterUniqueTogether(
            name='descuentoempleadonomina',
            unique_together={('empleado', 'descuento', 'nomina')},
        ),
        migrations.AlterUniqueTogether(
            name='competenciaempleado',
            unique_together={('id_competencia', 'id_empleado')},
        ),
        migrations.AlterUniqueTogether(
            name='capacitacionempleado',
            unique_together={('id_capacitacion', 'id_empleado')},
        ),
        migrations.AlterUniqueTogether(
            name='beneficioempleadonomina',
            unique_together={('empleado', 'beneficio', 'nomina')},
        ),
    ]
