# Generated by Django 5.1.6 on 2025-03-19 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_principal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='empleado',
            field=models.OneToOneField(blank=True, db_column='id_empleado', null=True, on_delete=django.db.models.deletion.CASCADE, to='app_principal.empleado'),
        ),
    ]
